// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw3-poBQh-5MmaEZXRAEMr0kMK0OAmGp4',
    appId: '1:56635991201:web:142ee56c1bb5b89f21bce0',
    messagingSenderId: '56635991201',
    projectId: 'aetheris-a0d38',
    authDomain: 'aetheris-a0d38.firebaseapp.com',
    storageBucket: 'aetheris-a0d38.firebasestorage.app',
    measurementId: 'G-CXBB9JVY3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMyxzsbh-M1Z9dp8_61vXyHCzlKK1H5m8',
    appId: '1:56635991201:android:a062e14954039c4321bce0',
    messagingSenderId: '56635991201',
    projectId: 'aetheris-a0d38',
    storageBucket: 'aetheris-a0d38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cNSSP1In-urM1GjT7ZxINOCdCc5kVVU',
    appId: '1:56635991201:ios:853f0c96f674f4e021bce0',
    messagingSenderId: '56635991201',
    projectId: 'aetheris-a0d38',
    storageBucket: 'aetheris-a0d38.firebasestorage.app',
    androidClientId: '56635991201-dd22ulndgo8ontckat598a7ls2va7644.apps.googleusercontent.com',
    iosClientId: '56635991201-k0p7aiqt359knd7nvhujfh3c7ktu9hhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cNSSP1In-urM1GjT7ZxINOCdCc5kVVU',
    appId: '1:56635991201:ios:853f0c96f674f4e021bce0',
    messagingSenderId: '56635991201',
    projectId: 'aetheris-a0d38',
    storageBucket: 'aetheris-a0d38.firebasestorage.app',
    androidClientId: '56635991201-dd22ulndgo8ontckat598a7ls2va7644.apps.googleusercontent.com',
    iosClientId: '56635991201-k0p7aiqt359knd7nvhujfh3c7ktu9hhm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw3-poBQh-5MmaEZXRAEMr0kMK0OAmGp4',
    appId: '1:56635991201:web:c3f8ad5f88cf6fdd21bce0',
    messagingSenderId: '56635991201',
    projectId: 'aetheris-a0d38',
    authDomain: 'aetheris-a0d38.firebaseapp.com',
    storageBucket: 'aetheris-a0d38.firebasestorage.app',
    measurementId: 'G-8S5F9ZLGQX',
  );
}
